name: FinEng
channels:
  - conda-forge
  - anaconda
  - pyviz
  - pytorch
  - defaults
dependencies:
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py36_1
  - openssl=1.0.2p=h14c3975_0
  - pandas-datareader=0.6.0=py36_0
  - requests-file=1.4.3=py36_0
  - requests-ftp=0.3.1=py36_0
  - wrapt=1.10.11=py36h14c3975_2
  - jupyterlab=0.34.12=py36_0
  - jupyterlab_launcher=0.13.1=py_2
  - appdirs=1.4.3=py36h28b3542_0
  - asn1crypto=0.24.0=py36_0
  - atomicwrites=1.2.1=py36_0
  - attrs=18.2.0=py36h28b3542_0
  - automat=0.7.0=py36_0
  - blas=1.0=mkl
  - bleach=2.1.4=py36_0
  - bokeh=0.13.0=py36_0
  - bzip2=1.0.6=h14c3975_5
  - cairo=1.14.12=h7636065_2
  - cartopy=0.16.0=py36hfa13621_0
  - cffi=1.11.5=py36he75722e_1
  - cftime=1.0.0b1=py36h035aef0_0
  - chardet=3.0.4=py36_1
  - click=7.0=py36_0
  - click-plugins=1.0.3=py36_1
  - cligj=0.4.0=py36_1
  - cloudpickle=0.5.6=py36_0
  - colorcet=1.0.0=py36_0
  - constantly=15.1.0=py36h28b3542_0
  - cryptography=2.3.1=py36hc365091_0
  - curl=7.61.1=hbc83047_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dask=0.18.1=py36_0
  - dask-core=0.18.1=py36_0
  - datashape=0.5.4=py36_1
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - descartes=1.1.0=py36_0
  - distributed=1.23.2=py36_0
  - entrypoints=0.2.3=py36_2
  - expat=2.2.6=he6710b0_0
  - fastparquet=0.1.6=py36h7b6447c_0
  - fiona=1.7.12=py36h3f37509_0
  - fontconfig=2.12.6=h49f89f6_0
  - freetype=2.8=hab7d2ae_1
  - freexl=1.0.5=h14c3975_0
  - gdal=2.2.2=py36hc209d97_1
  - geopandas=0.3.0=py36_0
  - geos=3.6.2=heeff764_2
  - giflib=5.1.4=h14c3975_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - hdf4=4.2.13=h3ca952b_2
  - hdf5=1.10.2=hba1933b_1
  - heapdict=1.0.0=py36_2
  - html5lib=1.0.1=py36_0
  - hyperlink=18.0.0=py36_0
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py36_0
  - imageio=2.4.1=py36_0
  - incremental=17.5.0=py36_0
  - intel-openmp=2019.0=118
  - ipykernel=5.0.0=py36h39e3cac_0
  - ipython=5.8.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.2=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=h024ee3a_2
  - json-c=0.13.1=h1bed415_0
  - jsonschema=2.6.0=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py36_0
  - kealib=1.4.7=h77bc034_6
  - kiwisolver=1.0.1=py36hf484d3e_0
  - krb5=1.16.1=hc83ff2d_6
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.61.1=heec0ca6_0
  - libdap4=3.19.1=h6ec2957_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgdal=2.2.4=h6f639c0_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libkml=1.3.0=h590aaf7_4
  - libnetcdf=4.6.1=h10edf3e_1
  - libpng=1.6.34=hb9fc6fc_0
  - libpq=10.5=h1ad7b7a_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.8.5=h20b78c2_2
  - libspatialite=4.3.0a=he475c7f_19
  - libssh2=1.8.0=h9cfc8f7_4
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - libxslt=1.1.32=h1312cb7_0
  - llvmlite=0.25.0=py36hd408876_0
  - locket=0.2.0=py36_1
  - lxml=4.2.5=py36hefd8a0e_0
  - markupsafe=1.0=py36h14c3975_1
  - matplotlib=2.2.2=py36h0e671d2_1
  - mistune=0.8.3=py36h14c3975_1
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py36h7dd41cf_0
  - mkl_random=1.0.1=py36h4414c95_1
  - more-itertools=4.3.0=py36_0
  - msgpack-python=0.5.6=py36h6bb024c_1
  - multipledispatch=0.6.0=py36_0
  - munch=2.3.2=py36_0
  - nbconvert=5.3.1=py36_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=hf484d3e_0
  - netcdf4=1.4.1=py36h4b4f87f_0
  - networkx=2.2=py36_1
  - ninja=1.8.2=py36h6bb024c_1
  - notebook=5.7.0=py36_0
  - numba=0.40.0=py36h962f231_0
  - numpy=1.15.2=py36h1d66e8a_1
  - numpy-base=1.15.2=py36h81de0dd_1
  - olefile=0.46=py36_0
  - openjpeg=2.3.0=h05c96fa_1
  - owslib=0.16.0=py36_0
  - packaging=18.0=py36_0
  - pandas=0.23.4=py36h04863e7_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - partd=0.3.8=py36_0
  - patsy=0.5.0=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=5.1.0=py36h3deb7b8_0
  - pip=10.0.1=py36_0
  - pixman=0.34.0=hceecf20_3
  - pluggy=0.7.1=py36h28b3542_0
  - poppler=0.65.0=ha54bb34_0
  - poppler-data=0.4.9=0
  - proj4=5.0.1=h14c3975_0
  - prometheus_client=0.3.1=py36h28b3542_0
  - prompt_toolkit=1.0.15=py36_0
  - psutil=5.4.7=py36h14c3975_0
  - psycopg2=2.7.5=py36hb7f436b_0
  - ptyprocess=0.6.0=py36_0
  - py=1.6.0=py36_0
  - pyasn1=0.4.4=py36h28b3542_0
  - pyasn1-modules=0.2.2=py36_0
  - pycparser=2.19=py36_0
  - pyepsg=0.3.2=py36_0
  - pygments=2.2.0=py36_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.1=py36_0
  - pyproj=1.9.5.1=py36h7b21b82_1
  - pyqt=5.9.2=py36h751905a_0
  - pysal=1.14.4.post1=py36_1
  - pyshp=1.2.12=py36_0
  - pysocks=1.6.8=py36_0
  - pytest=3.8.1=py36_0
  - python=3.6.6=hc3d631a_0
  - python-dateutil=2.7.3=py36_0
  - python-snappy=0.5.3=py36he6710b0_0
  - pytz=2018.5=py36_0
  - pywavelets=1.0.1=py36hdd07704_0
  - pyyaml=3.13=py36h14c3975_0
  - pyzmq=17.1.2=py36h14c3975_0
  - qt=5.9.5=h7e424d6_0
  - qtconsole=4.4.1=py36_0
  - readline=7.0=h7b6447c_5
  - requests=2.19.1=py36_0
  - rtree=0.8.3=py36_0
  - scikit-image=0.14.0=py36hf484d3e_1
  - scikit-learn=0.20.0=py36h4989274_1
  - scipy=1.1.0=py36hfa4b5c9_1
  - selenium=3.14.0=py36h14c3975_0
  - send2trash=1.5.0=py36_0
  - service_identity=17.0.0=py36h28b3542_0
  - setuptools=40.4.3=py36_0
  - shapely=1.6.4=py36h7ef4460_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36_1
  - snappy=1.1.7=hbae5bb6_3
  - sortedcontainers=2.0.5=py36_0
  - sqlalchemy=1.2.12=py36h7b6447c_0
  - sqlite=3.25.2=h7b6447c_0
  - statsmodels=0.9.0=py36h035aef0_0
  - streamz=0.3.0=py36_0
  - tblib=1.3.2=py36_0
  - terminado=0.8.1=py36_1
  - testpath=0.4.1=py36_0
  - thrift=0.11.0=py36hf484d3e_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=4.5.3=py36_0
  - traitlets=4.3.2=py36_0
  - twisted=18.7.0=py36h14c3975_1
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.32.0=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - xarray=0.10.9=py36_0
  - xerces-c=3.2.1=hac72e42_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.5=hf484d3e_1
  - zict=0.1.3=py36_0
  - zlib=1.2.11=ha838bed_2
  - zope=1.0=py36_1
  - zope.interface=4.5.0=py36h14c3975_0
  - pytorch-cpu=0.4.1=py36_cpu_1
  - datashader=0.6.7=py_0
  - geoviews=1.5.2=py_0
  - geoviews-core=1.5.2=py_0
  - holoviews=1.10.7=py_0
  - hvplot=0.2.1=py_0
  - param=1.7.0=py_0
  - parambokeh=0.2.3=py_0
  - paramnb=2.0.4=py_0
  - phantomjs=2.1.1=0
  - pyct=0.4.5=py_0
  - pyct-core=0.4.5=py_0
  - pyviz=0.9.11=py_0
  - pyviz_comms=0.6.0=py_0
  - rise=5.3.0=py36_0
  - pip:
    - beautifulsoup4==4.6.0
    - cssselect==1.0.3
    - feedfinder2==0.0.4
    - feedparser==5.2.1
    - jieba3k==0.35.1
    - msgpack==0.5.6
    - newspaper3k==0.2.6
    - nltk==3.2.5
    - tldextract==2.2.0
    - torch==0.4.1
prefix: /home/marcussky/anaconda3/envs/tulip

